//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class applytender
    {
        [DisplayName("Apply Id")]
        public int id { get; set; }
        [DisplayName("Tender ID")]
        [Required]
        public Nullable<int> tid { get; set; }
        [DisplayName("Contractor Id")]
        [Required]
        public string cid { get; set; }
        [DisplayName("Date of Apply")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy hh:mm}")]
        public Nullable<System.DateTime> applydate { get; set; }
        [DisplayName("Bid Amount")]
        [DisplayFormat(DataFormatString = "Rs.{0:N}")]
        public Nullable<decimal> bidamount { get; set; }
        [DisplayName("Application Status")]
        public string status { get; set; }
        [DisplayName("Document")]
        public string document { get; set; }
        [DisplayName("Approval Date")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> approvaldate { get; set; }

        public virtual contractor contractor { get; set; }
        public virtual tender tender { get; set; }
    }
}
