//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tender
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tender()
        {
            this.applytenders = new HashSet<applytender>();
        }

        [DisplayName("Tender Id")]
        public int tid { get; set; }
        [DisplayName("Tender Type")]
        [Required]
        public string ttype { get; set; }
        [DisplayName("Tender Date")]
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> tdate { get; set; }
        [DisplayName("Minimum Quote")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:N}")]
        public Nullable<decimal> minquote { get; set; }
        [DisplayName("Last Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public Nullable<System.DateTime> duedate { get; set; }
        [DisplayName("Description")]
        [Required]
        public string description { get; set; }
        [DisplayName("Tender Title")]
        [Required]
        public string title { get; set; }
        [DisplayName("Tender Status")]
        public string status { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<applytender> applytenders { get; set; }
    }
}
