//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract_Management
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class contractsdbEntities : DbContext
    {
        public contractsdbEntities()
            : base("name=contractsdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<contractor> contractors { get; set; }
        public virtual DbSet<tender> tenders { get; set; }
        public virtual DbSet<securityque> securityques { get; set; }
        public virtual DbSet<applytender> applytenders { get; set; }
    }
}
